### PR TITLE
Chore: update to Python 3.11

### PR DESCRIPTION
**Pull request by angela-tran**
Part of cal-itp/docker-python-web#23

When cal-itp/docker-python-web#24 is merged in, we will pick that up as our base image and require a code change to handle new behavior:

from https://docs.python.org/3.11/library/csv.html#csv.Dialect.quotechar,
> Changed in version 3.11: An empty quotechar is not allowed.

### CODE REVIEW

**Review by thekaveman — APPROVED** [review]

**Review by thekaveman — CHANGES_REQUESTED** [review]
Let's also update the version in `.github/workflows/.python-version`

**Review by thekaveman — DISMISSED** [review]

**Comment by thekaveman** [comment]
Arg, one more place -- in `pyproject.toml` under `tool.black`

**Comment by angela-tran** [comment]
> Arg, one more place -- in `pyproject.toml` under `tool.black`

Tricky one - thanks for catching that!

**Review by thekaveman — APPROVED** [review]
Yes I think this is all of them 🚀

**Comment by angela-tran** [comment]
Right after I merged this, I just noticed in Docker Desktop that there was a failure with the `docs` service for `eligibility-server` 😑 

```
2023-09-19 16:26:17 ERROR   -  Config value 'markdown_extensions': Failed to load extension 'fontawesome_markdown'.
2023-09-19 16:26:17   File "/home/calitp/.local/lib/python3.11/site-packages/fontawesome_markdown/__init__.py", line 1, in <module>
2023-09-19 16:26:17     from .main import FontAwesomePattern, FontAwesomeExtension, FontAwesomeException, makeExtension  # NOQA
2023-09-19 16:26:17     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-09-19 16:26:17   File "/home/calitp/.local/lib/python3.11/site-packages/fontawesome_markdown/main.py", line 4, in <module>
2023-09-19 16:26:17     from markdown.util import etree
2023-09-19 16:26:17 ImportError: cannot import name 'etree' from 'markdown.util' (/home/calitp/.local/lib/python3.11/site-packages/markdown/util.py)
2023-09-19 16:26:17 
2023-09-19 16:26:17 Aborted with 1 configuration errors!
```

I'll open a follow-up PR for this.

**Comment by thekaveman** [comment]
@angela-tran already fixed in #320

**Comment by angela-tran** [comment]
Yay, thanks!

**Comment by thekaveman** [comment]
Confirmed [the deploy to `dev`](https://github.com/cal-itp/eligibility-server/actions/runs/6241344720/job/16943362977#step:5:153) used the latest Python 3.11 image from [`docker-python-web`](https://github.com/cal-itp/docker-python-web/pkgs/container/docker-python-web/129497369?tag=2cd8d29e1de381828b7e09756833042788f008c9)

Look for the matching `sha256:7a8a6bc350c5ebffd04b3855912abeb3fb8a1b23c8578ad47c4a463a16a6070c`

**Pull request merged**
