### PR TITLE
Feat: version from git metadata

### LINKED ISSUE #287: Add support for app getting its version dynamically
May be able to use https://setuptools-git-versioning.readthedocs.io/en/stable/install.html#pyproject-toml

It'd be simplest if this can be done in a way that still works with the old deployment model in case we need to do a release while we're in the middle of working on the new deployment model (e.g. a hotfix). 

However, if this isn't compatible with our old deployment model, then we'll need to think more about when to merge this in.

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #287

I'm noticing that `setuptools_scm` seems to want an _annotated_ tag, because it uses

```
git describe
```

To get the version, which by default only lists annotated tags. See more: 

* https://setuptools-scm.readthedocs.io/en/latest/usage/#default-versioning-scheme
* https://git-scm.com/docs/git-describe#_description

### CODE REVIEW

**Comment by angela-tran** [comment]
@thekaveman I'm wondering if you know what's going on here: 

I checked out the `2023.11.1-pre1` tag, which is an annotated git tag. When I run `git describe`, I see `2023.11.1-pre1`. I rebuild the appcontainer by running `docker compose build server` and then rebuild the devcontainer. I run the app by hitting <kbd>F5</kbd>. I expect to see a log message that prints `Starting Eligibility Server 2023.11.1-pre1`, but instead I see `Starting Eligibility Server 2023.11.1rc2.dev0+gf91a4d1.d20231204`

I'm confused on where this is coming from. Have you seen this before?

image

**Comment by thekaveman** [comment]
> but instead I see Starting Eligibility Server `2023.11.1rc2.dev0+gf91a4d1.d20231204`

So I think what you're seeing is `setuptools_scm` computing what it thinks the _next_ version will be; see more here: https://setuptools-scm.readthedocs.io/en/latest/usage/#default-versioning-scheme

Question: do you have untracked changes locally? I think that is where the `dev0+gf91a4d1.d20231204` portion is coming from, essentially computing the "distance" from the most recent tag.

**Comment by angela-tran** [comment]
> Question: do you have untracked changes locally?

Ah yes, I did. I have removed all untracked changes now.

I've done as much as I can to start from a clean slate, i.e. I deleted all `eligibility_server` images and rebuilt the devcontainer without any caching. However, I'm still seeing a computed "next" version as the version number. 

For example, when I run `pip list`:
```
calitp@ab9899e30ff7:~/app$ pip list
Package                     Version                              Editable project location
--------------------------- ------------------------------------ -------------------------
aniso8601                   9.0.1
Babel                       2.13.1
black                       23.11.0
blinker                     1.7.0
bracex                      2.4
certifi                     2023.11.17
cffi                        1.16.0
cfgv                        3.4.0
charset-normalizer          3.3.2
click                       8.1.7
colorama                    0.4.6
coverage                    7.3.2
cryptography                41.0.7
Deprecated                  1.2.14
distlib                     0.3.7
eligibility-api             2023.9.1
eligibility-server          2023.11.1rc2.dev0+gf91a4d1.d20231204 /home/calitp/app
filelock                    3.13.1
flake8                      6.1.0
Flask                       2.3.3
...
```

@thekaveman What does your pip list show?

**Comment by thekaveman** [comment]
@angela-tran I think I know what is happening?

I was also seeing the same `pip list` output. And I noticed when rebuilding the devcontainer that the same version was being installed.

Then I checked out the tag itself:

```
git checkout 2023.11.1-pre1
```

Then

```
$ python -m setuptools_scm
2023.11.1rc1
```

So I think all this is saying is you're currently on a commit that is further in the future than the most recent tag, hence you must be on a new version, hence calculating that new version string.

(_I added `setuptools_scm` as a devcontainer dependency if you grab the latest commit on this branch_)

**Comment by angela-tran** [comment]
This can be closed if #382 is approved and merged

**Pull request merged**
