### PR TITLE
fix(devcontainer): configure git to install pre-commit

### LINKED ISSUE #473: Bug: Configure git to install pre-commit
## The bug

```
Running the postAttachCommand from devcontainer.json...

[127422 ms] Start: Run in container: /bin/bash .devcontainer/postAttach.sh
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /home/compiler/.cache/pre-commit/pre-commit.log

What's next:
    Try Docker Debug for seamless, persistent debugging tools in any container or image → docker debug 82179c5c37d960b0829f5d823b5b13fbd4ee069c859faf6490dcc989ec89858b
    Learn more at https://docs.docker.com/go/debug-cli/
[127976 ms] postAttachCommand failed with exit code 1. Skipping any further user-provided commands.
Done. Press any key to close the terminal
```

## The fix
Following https://github.com/cal-itp/benefits/pull/2027 https://github.com/cal-itp/docker-python-web/pull/36 https://github.com/cal-itp/benefits/pull/2017, apply the same fix to configure git to install pre-commit

### PR DESCRIPTION
**Pull request by machikoyasuda**
fixes #473 

I followed what @lalver1 did for Benefits here https://github.com/cal-itp/benefits/pull/2027 to fix this bug I got when I loaded the devcontainer on my macOS

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Closing this PR for now
Will get back to this after https://github.com/cal-itp/eligibility-server/pull/463 is merged

**Comment by thekaveman** [comment]
Oops :sweat: I didn't realize we hadn't merged #463 yet!

**Comment by thekaveman** [comment]
@machikoyasuda #463 is merged now

**Comment by machikoyasuda** [comment]
Ready for review now @thekaveman 

Re-tested this on rebased branch with the latest from `main`

**Review by thekaveman — APPROVED** [review]

**Pull request merged**
