### PR TITLE
Deploy to test

### PR DESCRIPTION
**Pull request by angela-tran**

### CODE REVIEW

**Comment by thekaveman** [comment]
Can we make #253 go as part of this cycle?

**Comment by thekaveman** [comment]
@angela-tran the `plan` failed, is that expected?

> Error: Instance cannot be destroyed
│ 
│   on key_vault.tf line 1:
│    1: resource "azurerm_key_vault" "main" {
│ 
│ Resource azurerm_key_vault.main has lifecycle.prevent_destroy set, but the
│ plan calls for this resource to be destroyed.

Seems like the same message as before?

**Comment by thekaveman** [comment]
Is this where we need to soft-delete the key vault and not worry since we're not trying to reuse the name anyway?

**Comment by angela-tran** [comment]
> @angela-tran the `plan` failed, is that expected?
> 
> > Error: Instance cannot be destroyed
> > │
> > │   on key_vault.tf line 1:
> > │    1: resource "azurerm_key_vault" "main" {
> > │
> > │ Resource azurerm_key_vault.main has lifecycle.prevent_destroy set, but the
> > │ plan calls for this resource to be destroyed.
> 
> Seems like the same message as before?

Right, it's the same message as when we `plan`'d the change in #354 for `dev`. So now we need to do the same process of manually deleting the Key Vault (this time the one named `eligibility-server-test`) and setting the secret again in the new `mst-courtesy-card-test` Key Vault

**Review by thekaveman — APPROVED** [review]

**Pull request merged**
