### PR TITLE
chore: check Terraform formatting as part of pre-commit

### PR DESCRIPTION
**Pull request by afeld**
Not sure if it makes sense to move any of this up to [docker-python-web](https://github.com/cal-itp/docker-python-web), but figured I'd show it working here first.

### CODE REVIEW

**Review by thekaveman — CHANGES_REQUESTED** [review]
Let's hold off on this until Courtesy Cards is launched.

**Review by thekaveman — COMMENTED** [review]
I wasn't able to build the devcontainer on this branch:

```sh
thekaveman MINGW64 ~/git/cal-itp/eligibility-server (feat/terraform-devcontainer)
$ bin/build.sh 
+ docker compose build --pull server
[+] Building 17.5s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                        0.1s 
 => => transferring dockerfile: 470B                                                                        0.0s 
 => [internal] load .dockerignore                                                                           0.1s 
 => => transferring context: 34B                                                                            0.0s 
 => [internal] load metadata for ghcr.io/cal-itp/docker-python-web:main                                     1.3s 
 => [internal] load build context                                                                           0.1s 
 => => transferring context: 23.08kB                                                                        0.0s 
 => CACHED [1/8] FROM ghcr.io/cal-itp/docker-python-web:main@sha256:164c4272e65714a58d70023978ae1a27c94ce3  0.0s 
 => [2/8] COPY requirements.txt requirements.txt                                                            0.2s 
 => [3/8] RUN pip install --no-cache-dir -r requirements.txt                                               10.6s 
 => [4/8] COPY bin/ bin/                                                                                    0.2s 
 => [5/8] COPY eligibility_server/ eligibility_server/                                                      0.1s 
 => [6/8] COPY *.py .                                                                                       0.1s 
 => [7/8] COPY README.md .                                                                                  0.2s 
 => [8/8] RUN pip install -e .                                                                              3.6s 
 => exporting to image                                                                                      0.8s 
 => => exporting layers                                                                                     0.7s 
 => => writing image sha256:8628a8a2e0472336c63b6eebf0b4b948c7cddf43090ecf87825a9ec8b51deb19                0.0s 
 => => naming to docker.io/library/eligibility_server:latest                                                0.0s 
+ docker compose build dev
[+] Building 1.6s (7/13)
 => [internal] load build definition from Dockerfile                                                        0.1s 
 => => transferring dockerfile: 679B                                                                        0.0s 
 => [internal] load .dockerignore                                                                           0.1s 
 => => transferring context: 34B                                                                            0.0s 
 => [internal] load metadata for docker.io/library/eligibility_server:latest                                0.0s 
 => [1/9] FROM docker.io/library/eligibility_server:latest                                                  0.9s 
 => [internal] load build context                                                                           0.1s 
 => => transferring context: 959B                                                                           0.0s 
 => [2/9] COPY .devcontainer/install_terraform.sh .devcontainer/install_terraform.sh                        0.1s 
 => ERROR [3/9] RUN ./.devcontainer/install_terraform.sh                                                    0.3s 
------
 > [3/9] RUN ./.devcontainer/install_terraform.sh:
#0 0.277 /bin/sh: 1: ./.devcontainer/install_terraform.sh: not found
------
failed to solve: executor failed running [/bin/sh -c ./.devcontainer/install_terraform.sh]: exit code: 127
```

**Comment by thekaveman** [comment]
Note this is the same if I run `docker compose build` directly:

```
$ docker compose build --no-cache dev
[+] Building 1.5s (7/13)
 => [internal] load build definition from Dockerfile                                                                 0.1s 
 => => transferring dockerfile: 679B                                                                                 0.0s 
 => [internal] load .dockerignore                                                                                    0.1s 
 => => transferring context: 34B                                                                                     0.0s 
 => [internal] load metadata for docker.io/library/eligibility_server:latest                                         0.0s 
 => [1/9] FROM docker.io/library/eligibility_server:latest                                                           0.9s 
 => [internal] load build context                                                                                    0.1s 
 => => transferring context: 959B                                                                                    0.0s 
 => [2/9] COPY .devcontainer/install_terraform.sh .devcontainer/install_terraform.sh                                 0.1s 
 => ERROR [3/9] RUN ./.devcontainer/install_terraform.sh                                                             0.3s 
------
 > [3/9] RUN ./.devcontainer/install_terraform.sh:
#0 0.272 /bin/sh: 1: ./.devcontainer/install_terraform.sh: not found
------
failed to solve: executor failed running [/bin/sh -c ./.devcontainer/install_terraform.sh]: exit code: 127
```

**Comment by afeld** [comment]
Hmmm, I can't reproduce... Anyone else?

Also, pre-commit.ci doesn't seem to have Terraform installed, and thus fails… I guess we'd need to create a special hook to install it or something?

**Comment by thekaveman** [comment]
> Also, pre-commit.ci doesn't seem to have Terraform installed, and thus fails… I guess we'd need to create a special hook to install it or something?

This seems pretty far outside the scope of what we should be working on.

**Comment by afeld** [comment]
K, not going to worry about this then.

**Pull request closed without merging**
