### PR TITLE
Chore: devcontainer setup

### LINKED ISSUE #121: Normalize devcontainer settings/extensions with benefits
We have a pretty good devcontainer setup in [`cal-itp/benefits`](https://github.com/cal-itp/benefits) in terms of the extensions installed and default settings.

Let's replicate all that over here to make them more consistent.

### LINKED ISSUE #125: Run setup.py on devcontainer attach
This is the corollary to #100, but for the devcontainer.

This will make the experience of getting the application running just a little faster by pre-initializing the database.

- [ ] Rename `.devcontainer/pre-commit.sh` to `.devcontainer/postAttach.sh` (also update the `devcontainer.json`)
- [ ] Add `python setup.py` to the post attach script

### PR DESCRIPTION
**Pull request by thekaveman**
Cleans up the devcontainer setup and normalizes with `benefits`:

* Initialize the database as part of devcontainer startup - closes #125 
* Get all the settings and extensions we like using - closes #121 
* Moves the `compose.yml` file to the root, so `docker compose` commands can be run from there

### ⚠️ Devs should update their `.env` file 

The file will need to move from inside the `.devcontainer/` directory to the root of the repository

### CODE REVIEW

**Review by angela-tran — APPROVED** [review]
This is great work - the dev experience is more consistent now 💯 

Tested locally by:
 - running `cp .devcontainer/.env .env`
 - rebuilding the `server` image with `docker compose build server`
 - choosing `Rebuild and Reopen in Container` in VS Code

**Comment by thekaveman** [comment]
@machikoyasuda want to make sure you see this and can run the containers without any issue!

**Review by machikoyasuda — APPROVED** [review]
In this PR or in a subsequent PR, the docs need to be updated to remove `cd .devcontainer` and note that `setup.py` is happening at app start. Otherwise, works great: I was able to move my .env file, build a new container, Rebuild and Reopen in Container, run the app, healthcheck and run all tests.

**Review by machikoyasuda — APPROVED** [review]
Great!

**Pull request merged**
