### PR TITLE
Chore: Create an issue template for new releases

### LINKED ISSUE #433: Create an issue template for new releases
Based on https://github.com/cal-itp/benefits/blob/dev/.github/ISSUE_TEMPLATE/release.yml

Noting the difference here that we don't need a branch/version bump as that comes from the annotated git tag. Generally follows the process in these docs https://github.com/cal-itp/littlepay?tab=readme-ov-file#release-a-new-version

See a recent example in #434

### PR DESCRIPTION
**Pull request by lalver1**
Closes #433 

This PR creates an [issue form template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) for new releases.

### CODE REVIEW

**Comment by lalver1** [comment]
One small thing to note is that this template's checklist contains an item for the release candidate and another for the regular release. This may cause confusion about what to use in the title of the ticket (`Make a Release: YYYY.0M.R` or `Make a Release: YYYY.0M.-rcR` ), but it should be clear that the ticket should have the regular release version in the title, not the release candidate version.

We could add `Release Type` to the form (similar to [benefits](https://github.com/cal-itp/benefits/blob/dev/.github/ISSUE_TEMPLATE/release.yml) but with `release-candidate` and `release` instead of `Regular` and `Hotfix`) but it seems too much to have to create two separate issues, one for release candidates and one for releases.

**Comment by thekaveman** [comment]
> ...it should be clear that the ticket should have the regular release version in the title, not the release candidate version.
>
> ...it seems too much to have to create two separate issues, one for release candidates and one for releases.

Yeah we definitely don't want two separate issues! Since the checklist includes an item for making a release candidate, I think you're right and we're good with just the one template as-is.

**Review by thekaveman — COMMENTED** [review]
@lalver1, can you see if it is possible to have a description / body in the issue that gets created?

E.g. it would be great if the text of the `markdown` field showed up in the issue, not just in the form for creating an issue from the template.

**Review by angela-tran — APPROVED** [review]
This looks great to me! It'll be so nice to use this rather than the copy-pasting we've been doing.

**Pull request merged**
